version: '2.1'

services:
  r1:
    build: .
    volumes:
      - ./volumes/quagga/r1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: quagga-router:dev
    privileged: true
    ports:
      #admin
      - 10011:2601
    networks:
      r1h10:
        ipv4_address: 172.16.10.2
      r1r2:
        ipv4_address: 172.16.30.2
  r2:
    volumes:
      - ./volumes/quagga/r2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/supervisord.conf:/etc/supervisord.conf:ro
    image: quagga-router:dev
    privileged: true
    ports:
      #admin
      - 10012:2601
    networks:
      r1r2:
        ipv4_address: 172.16.30.3
      r1h20:
        ipv4_address: 172.16.20.2
  
  h1:
    image: alpine
    privileged: true
    command: sh -c "ip route del default && ip route add default via 172.16.10.2 && top"
    networks:
      r1h10:
        ipv4_address: 172.16.10.3
  h2:
    image: alpine
    privileged: true
    command: sh -c "ip route del default && ip route add default via 172.16.10.2 && top"
    networks:
      r1h10:
        ipv4_address: 172.16.10.4
  h3:
    image: alpine
    privileged: true
    command: sh -c "ip route del default && ip route add default via 172.16.20.2 && top"
    networks:
      r1h20:
        ipv4_address: 172.16.20.3
  h4:
    image: alpine
    privileged: true
    command: sh -c "ip route del default && ip route add default via 172.16.20.2 && top"
    networks:
      r1h20:
        ipv4_address: 172.16.20.4  

networks:
  r1h10:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24
  r1h20:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.16.20.0/24
  r1r2:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.16.30.0/24
